version: "3.9"
services:
  db:
    image: mysql:8.3
    container_name: databridge-mysql
    env_file:
      - ./api/.env
    ports:
      - "3366:3306"
    volumes:
      - db_data:/var/lib/mysql

  db-test:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: databridge_test
    ports:
      - "3367:3306"

volumes:
  db_data:
